### ISSUE TITLE
Indicators should not intersect with wrapping titles

### ISSUE THREAD

**Issue by agreazel** [isubit/luggage_indicator#1]
Suggest decreasing the top margin on indicators specifically for any node view to decrease (move up and out of the way of wrapping titles).

**Comment by rlfrahm** [comment]
This happens anywhere a node title wraps to 2+ lines.

**Comment by agreazel** [comment]
... with long titles

**Comment by agreazel** [comment]
![screen shot 2015-02-10 at 10 39 19 am](https://cloud.githubusercontent.com/assets/4522574/6137243/e6bc09f2-b13c-11e4-9c52-10e5c4e74083.png)

**Comment by agreazel** [comment]
found that the h1 tag in suitcase.css has a width:100% and when that is turned off, the CSS styles from the indicator submodule of margin-right: 4em works.

**Comment by njbooher** [comment]
Fixed by #6. Closing.
